// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp6xmlLjGIGyQtrOOX0MN71WmgaZFLadY',
    appId: '1:672711225476:web:13df349b52668f37fe12d1',
    messagingSenderId: '672711225476',
    projectId: 'greentexi-dcf5b',
    authDomain: 'greentexi-dcf5b.firebaseapp.com',
    storageBucket: 'greentexi-dcf5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjp2MxhPk9M10Sp5iRwdDafAmgux8I6u0',
    appId: '1:672711225476:android:8161873c738f60affe12d1',
    messagingSenderId: '672711225476',
    projectId: 'greentexi-dcf5b',
    storageBucket: 'greentexi-dcf5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgK6fdBQKPE4tAU4yqQZCCn7AY0ZtJEig',
    appId: '1:672711225476:ios:b32b07b6a734c88afe12d1',
    messagingSenderId: '672711225476',
    projectId: 'greentexi-dcf5b',
    storageBucket: 'greentexi-dcf5b.appspot.com',
    iosBundleId: 'com.example.greenTexi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgK6fdBQKPE4tAU4yqQZCCn7AY0ZtJEig',
    appId: '1:672711225476:ios:e4f82cd9eb5cfc60fe12d1',
    messagingSenderId: '672711225476',
    projectId: 'greentexi-dcf5b',
    storageBucket: 'greentexi-dcf5b.appspot.com',
    iosBundleId: 'com.example.greenTexi.RunnerTests',
  );
}
